apiVersion: v1
kind: Pod
metadata:
  name: expense1
  labels:
    project: expense
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: hardware
            operator: In
            values:
            - gu
  containers:
  - name: nginx
    image: nginx
  